### ISSUE TITLE
Update the current team asap

### ISSUE THREAD

**Issue by raydwaipayan** [codeIIEST/codeIIEST.github.io#10]
Following changes are required:

- [ ] Move the 2020 batch to the alumi portion.
- [ ] Update cards for the current GS and Treasurer. GS - Suryansh Gupta, Treasurer - Arijit Saha
- [ ] Update professor in charge. [Prof. Shyamalendu kandar, IT](https://www.iiests.ac.in/IIEST/Faculty/it-shyamalenduk)
- [ ] Update rest of the club members with 2021 and 2022 batch.

**Comment by raydwaipayan** [comment]
@indrarahul2013 Can you merge the PR once it's in? 

Professor in charge has asked us to update it and let him know the link asap.

The new website is in progress. Once it is done, we hope to replace this 
with the new nuxt based web app.

**Comment by indrarahul** [comment]
@raydwaipayan Sure, I will merge the PR. I am sure @suri-kumkaran has also the permission to merge PRs.

**Comment by indrarahul** [comment]
Merged the PR.
